### ISSUE TITLE
add native s3 storage backend

### ISSUE THREAD

**Issue by ibotty** [rustic-rs/rustic_core#10]
I was having a look at implementing it myself, but found the backend traits to not be async.  I also found in the changelog, that async was removed in 0.4.  Is this going to change soonish again?  If so, I'll defer it.

I would use `rust-s3`, because afaict the official aws sdk is async only.  What do you think?

**Comment by Scandiravian** [comment]
X-posting what I wrote on the PR for visibility; I haven't abandoned the S3 changes, I simply haven't had the time to migrate the PR to the new repo. There's only a few items on my todo list before this one, so I hope to get to this sometime in October

I appreciate your patience 😊

**Comment by Scandiravian** [comment]
Finally had time to migrate the changes to the new repo :partying_face: 

@aawsome I've had a change to look into https://github.com/apache/incubator-opendal and play around with it a bit for a different project. It's pretty straight forward to use, so if you think this is the way to go I feel reasonably confident I'll be able to switch to that crate instead. I think that would be a big of a bigger effort to do it _the_ right way™_, since the abstraction in `choose.rs` should then only be used for initialising the opendal backend to benefit from the opendal abstraction.
