### ISSUE TITLE
Make error handling/recovery more ergonomic at the API boundary

### ISSUE THREAD

**Issue by petrpan26** [rustic-rs/rustic_core#329]
Right now RusticError is return to the API call but there's no way to programatically match on an error.

I have one particular use case that need this:

I need to create a repo if there's not already a repo at the s3 directory. But this prove to be quite difficult without public error kind.

**Comment by simonsan** [comment]
Hey, we're currently undergoing a bigger redesign and refactoring of the error types and the error handling strategy in rustic_core.

Also because currently use cases like yours are not easily supported and we keep discovering cases where the current setup doesn't suit us well for internal error handling.

So rest assured, your use case is an important one, we will just need to make some bigger, more fundamental changes in that regard.

**Comment by simonsan** [comment]
We added a new `RusticError` API, please check if your use case is fulfilled now: https://github.com/rustic-rs/rustic_core/releases/tag/rustic_core-v0.6.0

In case there are still problems, feel free to reopen.
